/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as generatedContractSol from "./GeneratedContract.sol";
export { Counter__factory } from "./Counter__factory";
