/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TaskPaymentContractInterface extends Interface {
  getFunction(
    nameOrSignature: "bob" | "completeTask" | "taskCompleted" | "taskPayment"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "bob", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taskCompleted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "taskPayment",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bob", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskCompleted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "taskPayment",
    data: BytesLike
  ): Result;
}

export interface TaskPaymentContract extends BaseContract {
  connect(runner?: ContractRunner | null): TaskPaymentContract;
  waitForDeployment(): Promise<this>;

  interface: TaskPaymentContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bob: TypedContractMethod<[], [string], "view">;

  completeTask: TypedContractMethod<[], [void], "nonpayable">;

  taskCompleted: TypedContractMethod<[], [boolean], "view">;

  taskPayment: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bob"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "taskCompleted"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "taskPayment"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
