/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  TaskPaymentContract,
  TaskPaymentContractInterface,
} from "../../GeneratedContract.sol/TaskPaymentContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_bob",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "bob",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "completeTask",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "taskCompleted",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "taskPayment",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60806040526611c37937e08000600155348015601a57600080fd5b506040516102ed3803806102ed833981016040819052603791605b565b600080546001600160a01b0319166001600160a01b03929092169190911790556089565b600060208284031215606c57600080fd5b81516001600160a01b0381168114608257600080fd5b9392505050565b610255806100986000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c806343bb8db514610051578063c09cec771461005b578063ddb5289a1461008b578063f7317f00146100a2575b600080fd5b6100596100bf565b005b60005461006e906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b61009460015481565b604051908152602001610082565b6002546100af9060ff1681565b6040519015158152602001610082565b6000546001600160a01b0316331461011e5760405162461bcd60e51b815260206004820152601f60248201527f4f6e6c7920426f622063616e2063616c6c20746869732066756e6374696f6e0060448201526064015b60405180910390fd5b60025460ff16156101715760405162461bcd60e51b815260206004820152601960248201527f5461736b20697320616c726561647920636f6d706c65746564000000000000006044820152606401610115565b6002805460ff1916600190811790915560008054915460405191926001600160a01b0316918381818185875af1925050503d80600081146101ce576040519150601f19603f3d011682016040523d82523d6000602084013e6101d3565b606091505b505090508061021c5760405162461bcd60e51b815260206004820152601560248201527414185e5b595b9d081d1bc8109bd88819985a5b1959605a1b6044820152606401610115565b5056fea264697066735822122011c3b902cb032f539fcd545d854da00babec94df47e2a339d124542b7a08dce164736f6c634300081c0033";

type TaskPaymentContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TaskPaymentContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TaskPaymentContract__factory extends ContractFactory {
  constructor(...args: TaskPaymentContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _bob: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_bob, overrides || {});
  }
  override deploy(
    _bob: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_bob, overrides || {}) as Promise<
      TaskPaymentContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): TaskPaymentContract__factory {
    return super.connect(runner) as TaskPaymentContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TaskPaymentContractInterface {
    return new Interface(_abi) as TaskPaymentContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TaskPaymentContract {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as TaskPaymentContract;
  }
}
