/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as generatedContractSol from "./GeneratedContract.sol";
export type { generatedContractSol };
export type { Counter } from "./Counter";
export * as factories from "./factories";
export { Counter__factory } from "./factories/Counter__factory";
export type { TestContract } from "./GeneratedContract.sol/TestContract";
export { TestContract__factory } from "./factories/GeneratedContract.sol/TestContract__factory";
export type { TestCounter } from "./GeneratedContract.sol/TestCounter";
export { TestCounter__factory } from "./factories/GeneratedContract.sol/TestCounter__factory";
